var SDK;
(function(k){var m=function(){function b(){}b.initSdkParams=function(a){b._initParams?a&&a():b.requestToRbsServer(b.r_host,b.r_bid,b.r_plat,b.r_user,a)};b.requestToRbsServer=function(a,c,e,d,f){var g="",l="";d&&(g="/"+d,l="/src");-1==a.indexOf("http")&&(a="//"+a);b.getData(a+g+"/rsdk-base-server"+l+"/h5/get_init_data/"+c+"/"+e+"/v1",function(a){a&&(b._initParams={rsdk_param:JSON.stringify(a)},b._initParams=b.parseUrlParamsIntoMap(window.location.search,b._initParams),console.log("\u521d\u59cb\u5316\u53c2\u6570\uff1a"+JSON.stringify(b._initParams)),
f&&f())})};b.parseUrlParamsIntoMap=function(a,b){b||(b={});if(-1!=a.indexOf("?")){a=a.substr(1).split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(2<d.length){var f=a[c].split(d[0]+"=");b[d[0]]=f[1]}else b[d[0]]=d[1]}}return b};Object.defineProperty(b,"resBaseUrl",{get:function(){var a=b.getParamByName("resbaseurl"),c=rsdkResbBseUrl;a&&(c=a);return c},enumerable:!0,configurable:!0});b.formatResUrl=function(a){var c=b.resBaseUrl;-1<a.indexOf("./")?a=a.replace("./",c):(0==a.indexOf("/")&&
(a=a.replace("/","")),a=c+a);0>a.indexOf("?v=")&&(a=rsdkVersion?-1==rsdkVersion.indexOf("?")?a+("?"+rsdkVersion.toString()):a+rsdkVersion.toString():a+("?v="+(new Date).getDate().toString()));return a};b.loadScripts=function(a,c){if(a){for(var e=[],d=[],f=0;f<a.length;f++){var g=a[f];-1<g.indexOf("?v=")&&(g=g.split("?")[0]);".css"==g.substr(g.length-4)&&d.push(a[f]);".js"==g.substr(g.length-3)&&e.push(a[f]);-1<g.indexOf(".js?")&&e.push(a[f])}b.loadingScriptsList.push({js:e,css:d,callback:c});0==b.isScriptsLoading&&
b.loadjs()}};b.loadjs=function(){b.isScriptsLoading=!0;var a=b.loadingScriptsList[0].js;"object"!=typeof a&&(a=[a]);for(var c=!0,e=0;e<a.length;e++)b.loadedScriptsFiles[a[e]]||(c=!1,b.loadedScriptsFiles[a[e]]=1);if(c)b.loadCss();else{var d=document.getElementsByTagName("head").item(0)||document.documentElement,f=[],g=a.length-1,l=function(c){f[c]=document.createElement("script");f[c].setAttribute("type","text/javascript");f[c].onload=f[c].onreadystatechange=function(){this.onload=this.onreadystatechange=
null;c!=g?l(c+1):(this.parentNode.removeChild(this),b.loadCss())};f[c].setAttribute("src",a[c]);d.appendChild(f[c])};l(0)}};b.loadCss=function(){for(var a=b.loadingScriptsList[0].css,c=b.loadingScriptsList[0].callback,e=!0,d=0;d<a.length;d++)b.loadedScriptsFiles[a[d]]||(e=!1,b.loadedScriptsFiles[a[d]]=1);if(e)b.loadingScriptsList.shift(),c&&c(),b.isScriptsLoading=!1,0<b.loadingScriptsList.length&&b.loadjs();else{var f=document.getElementsByTagName("head")[0]||document.documentElement,g=[],l=a.length-
1,h=function(d){g[d]=document.createElement("link");g[d].setAttribute("rel","stylesheet");g[d].setAttribute("type","text/css");g[d].setAttribute("async","true");g[d].onload=g[d].onreadystatechange=function(){this.onload=this.onreadystatechange=null;d!=l?h(d+1):(b.loadingScriptsList.shift(),c&&c(),b.isScriptsLoading=!1,0<b.loadingScriptsList.length&&b.loadjs())};g[d].setAttribute("href",a[d]);f.appendChild(g[d])};h(0)}};b.getSpid=function(){var a=b.getParamByName("rsdkspid");null==a&&(a="rgame");return a};
b.getAllParam=function(){if(b._initParams)return b._initParams;console.info("CommonUtil._initParams is empty,please waiting for init success!");return b._initParams};b.checkIsWanba=function(){var a=window.location.host;return-1<window.location.pathname.indexOf("wanba")||-1<a.indexOf("urlshare")||-1<a.indexOf("qzone")};b.getQueryParamValue=function(a,b){a=new RegExp("(^|&)"+a+"=([^&]*)(&|$)","i");var c=window.location.search;b&&(c=b.split("?")[1]);b=c.substr(1).match(a);return null!=b?decodeURI(b[2]):
null};b.getParamByName=function(a){var c=void 0,e=b.getAllParam().rsdk_param;e&&(e=decodeURIComponent(e),(e=JSON.parse(e))&&(c=e[a]));return c};b.replaceUrlParam=function(a,b,e){null==e&&(e="");var c=new RegExp("\\b("+b+"=).*?(&|$)");if(0<=a.search(c))return a.replace(c,"$1"+e+"$2");a=a.replace(/\?$/,"");return a+(0<a.indexOf("?")?"&":"?")+b+"="+e};b.formatStrToJson=function(a){if(-1!=a.indexOf('"'))return a;a=a.replace(/:/g,'":"');a=a.replace(/,/g,'","');a=a.replace(/http":"/g,"http:");a=a.replace(/https":"/g,
"https:");a=a.replace(/\[/g,'["');a=a.replace(/\]/g,'"]');a=a.replace(/{/g,'{"');a=a.replace(/}/g,'"}');a=a.replace(/"\[/g,"[");return a=a.replace(/\]"/g,"]")};b.isLocal=function(){var a=!1,b=window.location.hostname;if(-1<b.indexOf("192.168")||-1<b.indexOf("127.0.0.1"))a=!0;return a};b.isAndroidPlatform=function(){return"Android"==b.getMobileOperatingSystem()&&window.RSDKPlatform};b.isIOSPlatform=function(){return"iOS"==b.getMobileOperatingSystem()&&window.webkit};b.getMobileOperatingSystem=function(){var a=
navigator.userAgent||navigator.vendor||window.opera;return/windows phone/i.test(a)?"Windows Phone":/android/i.test(a)?"Android":/iPad|iPhone|iPod/.test(a)&&!window.MSStream?"iOS":"unknown"};b.setCookie=function(a,c,e){if("rsdk_login_user_name"==a){var d=b.getCookie(a);if(d&&""!=d&&window.RGameLogin){d=!1;0>c.indexOf("_")&&(d=!0);var f=c.split("_");c=window.RGameLogin.getAllLoginUserInfoFromCookie();for(var g=c.length,l=!1,h=g-1;0<=h;h--)if(f[0]==c[h][0]){1==d?c.splice(h,1):c[h][1]=f[1];l=!0;break}0==
l&&c.push(f);g=c.length;d="";for(h=0;h<g;h++)d=""==d?d+c[h].join("_"):d+("|"+c[h].join("_"));c=d}}d=a+"="+encodeURIComponent(c);0<e&&(g=new Date,g.setTime(g.getTime()+36E5*e),d=-1!=location.host.indexOf("rayjoy.com")?d+"; expires="+g.toUTCString()+";path=/;domain=rayjoy.com":d+"; expires="+g.toUTCString());document.cookie=d;try{window.localStorage&&(window.localStorage[a]=c)}catch(n){}};b.getCookie=function(a){for(var b,e=document.cookie.split("; "),d=0;d<e.length;d++){var f=e[d].split("=");if(f[0]==
a)return b=decodeURIComponent(f[1])}try{if(window.localStorage&&(b=window.localStorage[a],void 0!=b))return b=decodeURIComponent(b)}catch(g){}return""};b.delCookie=function(a){var c=new Date;c.setTime(c.getTime()-1);b.getCookie(a)&&(document.cookie=a+"=;expires="+c.toUTCString()+";path=/;domain=rayjoy.com");window.localStorage&&localStorage.removeItem(a)};b.postData=function(a,c){b.realRequest({method:"POST",url:a,sendcount:1,callback:c})};b.getData=function(a,c){b.realRequest({method:"GET",url:a,
sendcount:1,callback:c})};b.realRequest=function(a){var c=a.url,e=a.callback;if(c)if(e){var d=new XMLHttpRequest;if("GET"==a.method)d.open(a.method,c,!0),d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),d.send();else{var f=c.split("?");f[1]?(d.open(a.method,f[0],!0),d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),d.send(f[1])):(d.open(a.method,c,!0),d.send())}d.onreadystatechange=function(){if(4==d.readyState)if(400<=d.status||0==d.status)console.error("RSDK xhr.status:"+
d.status),0==d.status?10<=a.sendcount?e({ret:-1}):(console.error("RSDK resend url:"+c),a.sendcount+=1,console.error("RSDK sendcount:"+a.sendcount),b.realRequest(a)):(console.error(d.status+":"+c),e({ret:-1}));else try{e(JSON.parse(String(d.responseText)))}catch(h){var f=String(d.responseText);console.error("error res:"+f);var l=f.indexOf("{");f=f.substr(l);e(JSON.parse(String(f)))}}}else console.error("no onSuccess");else console.error("no url")};b.hasClass=function(a,b){return a.className.match(new RegExp("(\\s|^)"+
b+"(\\s|$)"))};b.addClass=function(a,c){b.hasClass(a,c)||(a.className+=" "+c)};b.removeClass=function(a,c){b.hasClass(a,c)&&(a.className=a.className.replace(new RegExp("(\\s|^)"+c+"(\\s|$)")," "))};b.log=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];if(b.isDebug&&a){c="";for(var e=0;e<a.length;e++)c="object"==typeof a[e]?c+(" "+JSON.stringify(a[e])):c+(" "+a[e]);console.log(c)}};Object.defineProperty(b,"appId",{get:function(){if(b._appId)return b._appId;if(b.r_plat){var a=b.r_bid,
c=b.r_plat.split("-");if(2==c.length){if("devsdk"==a)return b._appId=c[1],c[1];if(-1!=c[1].indexOf(parseInt(a)/1E3+""))return console.log("get app id from query param r_plat:"+c[1]),b._appId=c[1],c[1]}}b._appId=b.getParamByName("appid");return b._appId},set:function(a){b._appId=a},enumerable:!0,configurable:!0});Object.defineProperty(b,"tokenUrl",{get:function(){return b.getParamByName("tokenurl")},enumerable:!0,configurable:!0});b.formatLoginData=function(a,c){a={userId:b.loginUserInfo.pid,prefix:b.loginUserInfo.pid_prefix,
userType:a,token:b.loginUserInfo.rsdk_token,nickname:b.loginUserInfo.nickname,avatar:b.loginUserInfo.avatar,inviter_pid:b.loginUserInfo.inviter_pid,inviter_uid:b.loginUserInfo.inviter_uid};if(c)for(var e in c)a[e]||(a[e]=c[e]);return a};b.loadedScriptsFiles=[];b.isScriptsLoading=!1;b.loadingScriptsList=[];b._appId=null;b.loginUserInfo={};b.isDebug=!1;return b}();k.CommonUtil=m;(function(b){b.RET_LOGIN_SUCCESS="0";b.RET_LOGIN_FAIL="-1";b.RET_LOGIN_CANCEL="-2";b.RET_SUCCESS="0";b.RET_FAIL="-1";b.RET_CANCEL=
"-2"})(k.SDKCode||(k.SDKCode={}));(function(b){b.EVENT_NAME_COMPLETED_LOGIN="-1";b.EVENT_NAME_TUTORIAL_STEP="-2";b.EVENT_NAME_COMPLETED_REGITSTER="-3";b.EVENT_NAME_COMPLETED_PAY="-4";b.EVENT_NAME_LEVEL_UP="-5";b.EVENT_NAME_LOAD_END="-6";b.EVENT_NAME_TUTORIAL_END="-7"})(k.SDKCode||(k.SDKCode={}));m=function(){function b(){}b.encode=function(a){var c="",e=0;for(a=b._utf8_encode(a);e<a.length;){var d=a.charCodeAt(e++);var f=a.charCodeAt(e++);var g=a.charCodeAt(e++);var l=d>>2;d=(d&3)<<4|f>>4;var h=(f&
15)<<2|g>>6;var k=g&63;isNaN(f)?h=k=64:isNaN(g)&&(k=64);c=c+b._keyStr.charAt(l)+b._keyStr.charAt(d)+b._keyStr.charAt(h)+b._keyStr.charAt(k)}return c};b._utf8_encode=function(a){a=a.replace(/\r\n/g,"\n");for(var b="",e=0;e<a.length;e++){var d=a.charCodeAt(e);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b};b._keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
return b}();k.Base64=m;m=function(){function b(){}b.encrypt=function(a){var b=window.CryptoJS.enc.Utf8.parse("Hra1502YJ2ogAym5"),e=window.CryptoJS.enc.Utf8.parse("cGluZzE5ODgwNzE3"),d="";"string"==typeof a?(a=window.CryptoJS.enc.Utf8.parse(a),d=window.CryptoJS.AES.encrypt(a,b,{iv:e,padding:window.CryptoJS.pad.ZeroPadding})):"object"==typeof a&&(a=JSON.stringify(a),a=window.CryptoJS.enc.Utf8.parse(a),d=window.CryptoJS.AES.encrypt(a,b,{iv:e,padding:window.CryptoJS.pad.ZeroPadding}));return d.toString()};
b.formatRequestData=function(a){"string"==typeof a&&(a=JSON.parse(a));"object"==typeof a&&(a.app_id=k.CommonUtil.appId,a.lang="cn",a.udid="h5");a={data:encodeURIComponent(JSON.stringify(a))};a=b.encrypt(JSON.stringify(a));return a=b.formatStrForServer(a)};b.formatStrForServer=function(a){return a=encodeURIComponent(a)};b.postData=function(a,c,e){c=b.formatRequestData(c);k.CommonUtil.postData(a+"?a="+c+"&t=h5",function(a){e&&e(a);(void 0==a.ret||0!=Number(a.ret))&&a.msg&&(window.RGameLogin?window.RGameLogin.showTip(a.msg):
console.log(a.msg))})};b.getData=function(a,c,e,d){d||(d="");c=b.formatRequestData(c);k.CommonUtil.getData(a+"?a="+c+d,function(a){e&&e(a);(void 0==a.ret||0!=Number(a.ret))&&a.msg&&(window.RGameLogin?window.RGameLogin.showTip(a.msg):console.log(a.msg))})};return b}();k.NetworkUtil=m})(SDK||(SDK={}));
var productInfo=function(){return function(){this.privateData=this.userId=this.os=this.currency=this.roleVipLevel=this.roleLevel=this.gameUserName=this.gameUserId=this.serverId=this.productType=this.productCount=this.coinNum=this.productName=this.productId=this.price=""}}();
