var h5limiplugin=function(){function a(){}a.init=function(b){console.log("GameStatusInfo:"+JSON.stringify(window.LimiGameStatusInfo));window.LimiGameStatusInfo?(b&&b(),a.initParams()):window.localStorage.getItem("LimiGameStatusInfo")?(console.log("INIT GET GameStatusInfo from localStorage"),window.LimiGameStatusInfo=JSON.parse(window.localStorage.getItem("LimiGameStatusInfo")),a.initParams(),b&&b()):b&&(window.LimiInitCallback=function(){a.initParams();b&&b()})};a.initParams=function(b){a.qqversion=
window.LimiGameStatusInfo.QQVer.replace(/\./g,"").slice(0,3);console.log("limi qqversion:"+a.qqversion);a.openid=window.LimiGameStatusInfo.openId;console.log("limi openid:"+a.openid);if(window.LimiGameStatusInfo.gameParam){var c=JSON.parse(window.LimiGameStatusInfo.gameParam);c&&c.inviter_pid&&c.inviter_uid&&(a.inviter_pid=c.inviter_pid,a.inviter_uid=c.inviter_uid)}window.LimiBK&&window.LimiBK.QQ&&window.LimiBK.MQQ&&(window.LimiBK.QQ.fetchOpenKey(function(d,c,e){console.log("limi openkey errCode:"+
d+" data:"+JSON.stringify(e)+" cmd:"+c);0==d&&(console.log("limi openkey:"+e.openKey),a.openKey=e.openKey,b&&b())}),window.LimiBK.MQQ.Account.getHead(a.openid,function(b,c){b==a.openid&&(a.user_avatar=c)}),window.LimiBK.MQQ.Account.getNick(a.openid,function(b,c){b==a.openid&&(a.user_nick=c)}))};a.login=function(b,c){a.openid?a.sendDataToRsdkServer(a.openid,"","","",b):a.initParams(function(){a.sendDataToRsdkServer(a.openid,"","","",b)})};a.sendDataToRsdkServer=function(b,c,d,f,e){RSDK.RSDKManager.getToken({pid:b,
big_app_id:SDK.CommonUtil.r_bid,sign:c,token:d,custom_data:"",sdk_platform:SDK.CommonUtil.r_plat,rsdk_server_version:"v1",login_time:f},function(b){if("ok"==b.status){if(e){var c=b.rsdk_ret.pid_prefix;b=b.rsdk_ret.pid;a.share_pid=c+b;SDK.CommonUtil.loginUserInfo={pid:c+b,pid_prefix:c,rsdk_token:"",username:a.user_nick,nickname:a.user_nick,avatar:a.user_avatar,inviter_pid:a.inviter_pid,inviter_uid:a.inviter_uid};e(SDK.SDKCode.RET_SUCCESS,SDK.CommonUtil.formatLoginData(""))}}else e&&e(SDK.SDKCode.RET_FAIL,
{})})};a.checkShare=function(){return 1};a.share=function(b,c){console.log("SHARE CONTENT:"+JSON.stringify(b));window.LimiBK.QQ.shareToArk(0,b.desc,b.imageurl,!0,a.share_ext,function(a,b,e){console.log("share code :"+a);0==a&&c(SDK.SDKCode.RET_SUCCESS,{})})};a.setShareInfo=function(b,c){a.game_user_id=c;window.rsdkShareDesc=b.desc;window.rsdkShareImgUrl=b.imageurl;a.share_ext=JSON.stringify({inviter_pid:a.share_pid,inviter_uid:a.game_user_id});window.rsdkShareExt=a.share_ext};a.pay=function(b,c){console.log(JSON.stringify(b));
a.openKey?a.goToPay(b,c):a.initParams(function(){a.goToPay(b,c)})};a.goToPay=function(b,c){var d={};d.cp_private=b.privateData?b.privateData:"";d.openid=a.openid;d.openkey=a.openKey;b.privateData=JSON.stringify(d);RSDK.RSDKManager.getOrderId(b,function(b){console.log(JSON.stringify(b));"PayPurchase"==b.status&&b.itemId?"lowQQVersion"==a.payPurchase(b.itemId,b.orderId)&&c&&c(4,{msg:"needReBuyItem"}):"rollback"==b.status?a.rollbackItem(b.itemId,b.seq):"ok"==b.status&&console.log("purchase success")})};
a.rollbackItem=function(a,c){c=[{id:parseInt(a),num:1,seq:c}];console.log("RollbackItem :"+JSON.stringify(c));window.LimiBK.QQ.rollbackGameItems?window.LimiBK.QQ.rollbackGameItems(c,function(b,c,e){console.log("Code :"+b+";SUCCESS LIST:"+JSON.stringify(c)+";FAIL LIST:"+JSON.stringify(e));if(0==b)for(b=0;b<c.length;b++)c[b]==parseInt(a)&&console.log("RollbackItem SUCCESS")}):console.log("BK.QQ.rollbackGameItems IS NOT A FUNCTION")};a.payPurchase=function(b,c){window.LimiBK.QQ.qPayPurchase(1,!0,[{itemId:b,
itemNum:1}],function(d,f){console.log("qPayPurchase errCode:"+d+" data:"+JSON.stringify(f));0==d&&(console.log("\u8d2d\u4e70\u6210\u529f\uff0c\u5411\u540e\u7aef\u53d1\u8d27"),a.sendPayDataToRsdkServer(b,c))});if(765>a.qqversion)return"lowQQVersion"};a.sendPayDataToRsdkServer=function(b,c){var d=SDK.CommonUtil.getParamByName("pay_url");d=d+"?openid="+a.openid+"&openkey="+a.openKey+"&ray_order_id="+c+"&itemid="+b;SDK.CommonUtil.postData(d,function(b){console.log("sendPayDataToRsdkServer RET:"+JSON.stringify(b));
"rollback"==b.status&&a.rollbackItem(b.itemid,b.seq)})};a.getCustomerServiceType=function(){return SDK.CommonUtil.getParamByName("h5lm_parms")&&SDK.CommonUtil.getParamByName("h5lm_parms").customer_type?SDK.CommonUtil.getParamByName("h5lm_parms").customer_type:0};a.getCustomerServiceData=function(b){if(SDK.CommonUtil.getParamByName("h5lm_parms")){var a={},d=SDK.CommonUtil.getParamByName("h5lm_parms");d.qq&&(a.qq=d.qq);d.qq_group&&(a.qq_group=d.qq_group);d.tel&&(a.tel=d.tel);console.log("cs info:"+
JSON.stringify(a));b(a)}};a.callSdk=function(b,c,d){"setAppBackgroundChangeCallback"==b?a.AppForegroundStatusChangeCallback=d:"reportGameResult"==b?(console.log("ReportGameResult:"+JSON.stringify(c)),window.LimiBK.QQ.reportGameResult(c,function(a,b,c){console.log(a);0!==a?d&&d(SDK.SDKCode.RET_FAIL):(console.log("\u4e0a\u62a5\u8fd0\u8425\u7ed3\u679c\u6210\u529f"),d&&d(SDK.SDKCode.RET_SUCCESS))})):"isUserInRedPackageActivity"==b?(console.log("rsdk isUserInRedPackageActivity"),b=window.LimiBK.QQ.isUserInRedPackageActivity(),
console.log("isUserInRedPackageActivity:"+b),d(b)):"redPackageButtonEvent"==b&&(console.log("redPackageButtonEvent"),window.LimiBK.QQ.redPackageButtonEvent())};a.inviter_pid="";a.inviter_uid="";a.user_avatar="";a.user_nick="";return a}();
