var pttracker;
(function(c){c.isDebug=!1;c.init=function(a,b){d.setHostAddress(b);a()};c.analyticsUser=function(a,b){switch(a){case e.ANALYTICS_TYPE_SET_GAME_INFO:f.sendGameInfoToSDK(b)}};c.analyticsBI=function(a,b){switch(a){case e.ANALYTICS_TYPE_BI_TUTORIAL:f.sendTutorialToBI(b);break;case e.ANALYTICS_TYPE_BI_HEARTBEAT:f.sendHeartbeatToBI(b)}};var k=function(){return function(){}}();c.GameUserInfo=k;var e=function(){function a(){}a.ANALYTICS_TYPE_SET_GAME_INFO=0;a.ANALYTICS_TYPE_BI_LOGIN=10;a.ANALYTICS_TYPE_BI_TUTORIAL=11;
a.ANALYTICS_TYPE_BI_HEARTBEAT=12;return a}();c.AnalyticsType=e;var f=function(){function a(){}a.open=function(){if(a._opened)console.log("pttracker opened");else{console.log("pttracker:opening...");var b=d.getStatisticHostAddress()+"/api/pingback/open",c={app_id:SDK.CommonUtil.appId,udid:"h5",lang:"cn"};c=JSON.stringify(c);SDK.NetworkUtil.getData(b,c,function(b){!b||0!=b.ret&&-3!=b.ret?console.warn(b):a._opened=!0},"&t=h5")}};a.sendGameInfoToSDK=function(b){var c=SDK.CommonUtil.appId;b.channelId&&
(SDK.CommonUtil.appId=b.channelId,console.log("pttrackert sendGameInfoToSDK app_id:"+SDK.CommonUtil.appId));a.open();var h=d.getStatisticHostAddress()+"/api/pingback/set_game_info";a.saveAndsendDataToBi(h,{app_id:SDK.CommonUtil.appId,udid:"h5",user_id:b.userId?b.userId:SDK.CommonUtil.loginUserInfo.pid,game_user_id:b.gameUserId,game_server_id:b.serverId,regist_time:b.registTime?b.registTime:b.registerTime,lang:"cn"},function(){a.sendHeartbeatToBI(b)});SDK.CommonUtil.appId=c;console.log("pttrackert real sub_app_id:"+
SDK.CommonUtil.appId)};a.sendTutorialToBI=function(b){var c=SDK.CommonUtil.appId;b.channelId&&(SDK.CommonUtil.appId=b.channelId,console.log("pttrackert sendTutorialToBI app_id:"+SDK.CommonUtil.appId));a.open();b={user_id:b.gameUserId,channel:SDK.CommonUtil.appId,step:b.firstexperienceStep?b.firstexperienceStep:b.step,zid:b.serverId,timestamp:Math.floor((new Date).getTime()/1E3).toString()};a.saveAndsendDataToBi(d.sDebug_bi_host_address+"/v1/user/tutorial",b);SDK.CommonUtil.appId=c};a.sendHeartbeatToBI=
function(b){var c=SDK.CommonUtil.appId;b.channelId&&(SDK.CommonUtil.appId=b.channelId,console.log("pttrackert sendHeartbeatToBI app_id:"+SDK.CommonUtil.appId));a.open();var h={user_id:b.gameUserId,channel:SDK.CommonUtil.appId,zid:b.serverId,timestamp:Math.floor((new Date).getTime()/1E3).toString(),udid:"h5"};a._heartBeatData=b;a.saveAndsendDataToBi(d.sDebug_bi_host_address+"/v1/user/heartbeat",h);a._heartBeatTime&&(clearTimeout(a._heartBeatTime),a._heartBeatTime=0);a._heartBeatTime=setTimeout(function(){a._heartBeatData&&
(a._heartBeatTime&&(clearTimeout(a._heartBeatTime),a._heartBeatTime=0),a.sendHeartbeatToBI(a._heartBeatData))},3E5);SDK.CommonUtil.appId=c};a.saveAndsendDataToBi=function(a,c,d){SDK.NetworkUtil.getData(a,c,function(a){a&&0==a.ret&&d&&d()},"&t=h5")};a._opened=!1;return a}();c.AnalyticsManager=f;var d=function(){function a(){}a.getHostIp=function(){return c.isDebug?"//54.201.212.55":"//54.186.154.125"};a.setHostAddress=function(b){b&&(a.hostStr=b);SDK.CommonUtil.isDebug&&console.log("pttracker:host:"+
a.hostStr);a.sDebug_bi_host_address=a.getBiagent()+g.BI_SERVICE;a.sDebug_bi_host_address_backup=a.getBiagent()+g.BI_SERVICE;b=a.hostStr;null==b||""==b?(a.sDebug_statistic_hoat_address=a.getBiagent(),a.sDebug_statistic_hoat_address_backup=a.getBiagent()):(a.sDebug_statistic_hoat_address=a.getBiagent_backup(),a.sDebug_statistic_hoat_address_backup=a.getBiagent_backup());SDK.CommonUtil.isDebug&&(console.log("pttracker:statistic host:"+a.sDebug_statistic_hoat_address),console.log("pttracker:bi host:"+
a.sDebug_bi_host_address));a.language="cn"};a.getStatisticHostAddress=function(){return a.sDebug_statistic_hoat_address};a.getBiagent=function(){return"//"+a.hostStr};a.getBiagent_backup=function(){return"//"+a.hostStr+g.BI_SERVICE};a.hostStr="";return a}();c.NetworkUtil=d;var g;(g=c.Constants||(c.Constants={})).BI_SERVICE="/bi-agent"})(pttracker||(pttracker={}));
